//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGSB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGSB.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , continuous display mode.
        /// </summary>
        internal static string CONTINUOUS_DISPLAY {
            get {
                return ResourceManager.GetString("CONTINUOUS_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , filtered on [{0}] &gt;.
        /// </summary>
        internal static string FILTERED_ON {
            get {
                return ResourceManager.GetString("FILTERED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;Invalid parameters.
        /// </summary>
        internal static string INVALID_PARAMETERS {
            get {
                return ResourceManager.GetString("INVALID_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;Data capture is currently on pause, you need to start first.
        /// </summary>
        internal static string NEED_TO_RESTART {
            get {
                return ResourceManager.GetString("NEED_TO_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIPTION.
        /// </summary>
        internal static string SUBSCRIPTION {
            get {
                return ResourceManager.GetString("SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO;SUBSCRIPTION, continuous display mode{(string.IsNullOrEmpty(IGClient.Filter) ? &quot;&quot; : $&quot;, filtered on [{IGClient.Filter}]&quot;)} &gt;.
        /// </summary>
        internal static string SUBSCRIPTION_CONTINUOUS {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_CONTINUOUS", resourceCulture);
            }
        }
    }
}
