//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGSB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGSB.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Schema is active.
        /// </summary>
        internal static string ACTIVATE_SCHEMA {
            get {
                return ResourceManager.GetString("ACTIVATE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Cannot embed short codes within short codes.
        /// </summary>
        internal static string CANNOT_EMBED_CODES {
            get {
                return ResourceManager.GetString("CANNOT_EMBED_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Checking password strength.
        /// </summary>
        internal static string CHECK_PASSWORD {
            get {
                return ResourceManager.GetString("CHECK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;DATASET, continuous display mode, filtered on [{0}] &gt;&gt;.
        /// </summary>
        internal static string CONTINUOUS_DATASET {
            get {
                return ResourceManager.GetString("CONTINUOUS_DATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;PREDICTION, continuous display mode, filtered on [{0}] &gt;&gt;&gt;.
        /// </summary>
        internal static string CONTINUOUS_PREDICTION {
            get {
                return ResourceManager.GetString("CONTINUOUS_PREDICTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;SUBSCRIPTION, continuous display mode, filtered on [{0}] &gt;.
        /// </summary>
        internal static string CONTINUOUS_SUBSCRIPTION {
            get {
                return ResourceManager.GetString("CONTINUOUS_SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Dataset emptied.
        /// </summary>
        internal static string DATASET_EMPTIED {
            get {
                return ResourceManager.GetString("DATASET_EMPTIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Type &apos;help&apos; or &apos;/?&apos; for available commands.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Schema has been made not active.
        /// </summary>
        internal static string INACTIVATE_SCHEMA {
            get {
                return ResourceManager.GetString("INACTIVATE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Invalid parameters.
        /// </summary>
        internal static string INVALID_PARAMETERS {
            get {
                return ResourceManager.GetString("INVALID_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;IGSB.Program ERROR: Missing some or all command line arguments\nss = Map to source key in settings file (mandatory i.e. Demo, Live), case sensitive\nwf = Name of watch file to use (mandatory)\nst = Settings file name (optional, defaults to settings.json)\ncp = Password to use for encrypting settings file (optional, but will be prompted if not supplied).
        /// </summary>
        internal static string MISSING_ARGS {
            get {
                return ResourceManager.GetString("MISSING_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Data capture is currently on pause, you need to &apos;begin&apos; first.
        /// </summary>
        internal static string NEED_TO_RESTART {
            get {
                return ResourceManager.GetString("NEED_TO_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Unable to authenticate and start.
        /// </summary>
        internal static string NO_AUTHENTICATION {
            get {
                return ResourceManager.GetString("NO_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;No dataset found.
        /// </summary>
        internal static string NO_DATASET {
            get {
                return ResourceManager.GetString("NO_DATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;No log file found.
        /// </summary>
        internal static string NO_LOGFILE {
            get {
                return ResourceManager.GetString("NO_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;No model found.
        /// </summary>
        internal static string NO_MODEL {
            get {
                return ResourceManager.GetString("NO_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;No model found or cannot overwrite existing model.
        /// </summary>
        internal static string NO_MODEL_FOUND {
            get {
                return ResourceManager.GetString("NO_MODEL_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Schema not found.
        /// </summary>
        internal static string NO_SCHEMA {
            get {
                return ResourceManager.GetString("NO_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;No schema found or cannot overwrite existing dataset.
        /// </summary>
        internal static string NO_SCHEMA_FOUND {
            get {
                return ResourceManager.GetString("NO_SCHEMA_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Settings parameters ok.
        /// </summary>
        internal static string PARAMETERS_OK {
            get {
                return ResourceManager.GetString("PARAMETERS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Password failed.
        /// </summary>
        internal static string PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;You must reload watch file to see changes.
        /// </summary>
        internal static string RELOAD_WATCH {
            get {
                return ResourceManager.GetString("RELOAD_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Reserved shortcode, you cannot assign anything to that code.
        /// </summary>
        internal static string RESERVED_SHORTCODE {
            get {
                return ResourceManager.GetString("RESERVED_SHORTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info;Type &apos;begin&apos; or &apos;/bc&apos; to begin collecting data.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;Unknown command, /? for help.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error;A weak password has been supplied.
        /// </summary>
        internal static string WEAK_PASSWORD {
            get {
                return ResourceManager.GetString("WEAK_PASSWORD", resourceCulture);
            }
        }
    }
}
