//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGSB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGSB.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continuous display mode.
        /// </summary>
        internal static string CONTINUOUS_DISPLAY {
            get {
                return ResourceManager.GetString("CONTINUOUS_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO;Dataset emptied.
        /// </summary>
        internal static string DATASET_EMPTIED {
            get {
                return ResourceManager.GetString("DATASET_EMPTIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtered on .
        /// </summary>
        internal static string FILTERED_ON {
            get {
                return ResourceManager.GetString("FILTERED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;Invalid parameters.
        /// </summary>
        internal static string INVALID_PARAMETERS {
            get {
                return ResourceManager.GetString("INVALID_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;Data capture is currently on pause, you need to &apos;begin&apos; first.
        /// </summary>
        internal static string NEED_TO_RESTART {
            get {
                return ResourceManager.GetString("NEED_TO_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;No dataset found.
        /// </summary>
        internal static string NO_DATASET {
            get {
                return ResourceManager.GetString("NO_DATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;No log file found.
        /// </summary>
        internal static string NO_LOGFILE {
            get {
                return ResourceManager.GetString("NO_LOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;No model found.
        /// </summary>
        internal static string NO_MODEL {
            get {
                return ResourceManager.GetString("NO_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;No model found or cannot overwrite existing model.
        /// </summary>
        internal static string NO_MODEL_FOUND {
            get {
                return ResourceManager.GetString("NO_MODEL_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;Schema not found.
        /// </summary>
        internal static string NO_SCHEMA {
            get {
                return ResourceManager.GetString("NO_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;No schema found or cannot overwrite existing dataset.
        /// </summary>
        internal static string NO_SCHEMA_FOUND {
            get {
                return ResourceManager.GetString("NO_SCHEMA_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO;SUBSCRIPTION.
        /// </summary>
        internal static string SUBSCRIPTION {
            get {
                return ResourceManager.GetString("SUBSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR;Unknown command, /? for help.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
    }
}
